name: 'Create npm workspace release'
description: 'Determine the path of an NPM workspace from the name of a release created using api.video-release-from-workspaces-changelogs-action'
inputs:
  github-auth-token:  
    description: 'The GitHub auth token'
    required: true
outputs:
  response: # id of output
    description: 'The result of the operation'
runs:
  using: 'node12'
  main: 'dist/index.js'